---
# configure_borg_backup_server/tasks/main.yml

- name: "Create group {{ borg_user }}"
  ansible.builtin.group:
    name: "{{ borg_user }}"
    state: 'present'
    gid: "{{ borg_group_gid }}"
    system: true

- name: "Create user {{ borg_user }}"
  ansible.builtin.user:
    name: "{{ borg_user }}"
    state: 'present'
    uid: "{{ borg_user_uid }}"
    group: "{{ borg_user }}"
    groups: "{{ borg_user }}"
    password: "{{ borg_user_password }}"
    update_password: 'on_create'
    home: "{{ borg_home_directory }}"
    create_home: true
    shell: '/bin/bash'
    system: true

- name: 'Set permissions on HOME directory for the borg user'
  ansible.builtin.file:
    path: "{{ borg_home_directory }}"
    state: 'directory'
    owner: "{{ borg_user }}"
    group: "{{ borg_user }}"
    mode: '0700'

- name: 'Create .ssh/ folder for the borg user'
  ansible.builtin.file:
    path: "{{ borg_home_directory }}/.ssh/"
    state: 'directory'
    owner: "{{ borg_user }}"
    group: "{{ borg_user }}"
    mode: '0700'

- name: 'Create authorized_keys file for borg user'
  ansible.posix.authorized_key:
    user: "{{ borg_user }}"
    state: 'present'
    key: "{{ borg_ssh_public_key }}"
    key_options: 'command="/usr/bin/borg serve --restrict-to-path {{ borg_home_directory }}",restrict'
    path: "{{ borg_ssh_authorizedkeys_path }}"
